# Generated by Django 2.2.3 on 2020-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_auto_20200509_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verify',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
