# Generated by Django 2.2.3 on 2020-05-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0006_auto_20200509_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='verify_email',
        ),
    ]
