# Generated by Django 2.2.3 on 2020-05-09 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0007_auto_20200509_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
