# Generated by Django 2.2.3 on 2020-05-09 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0008_auto_20200509_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verify_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='verify',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
