# Generated by Django 2.2.3 on 2020-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0015_orderitem_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='product_pic1',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='product_pic2',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='product_pic3',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
