# Generated by Django 2.2.3 on 2020-05-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0016_auto_20200512_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='ShopApp.Sizes'),
        ),
    ]
