# Generated by Django 2.2.3 on 2020-05-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0017_auto_20200512_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='product_pic',
            new_name='product_pic0',
        ),
    ]
