# Generated by Django 2.2.3 on 2020-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0022_transactions_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='order_size',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
