# Generated by Django 2.2.3 on 2020-05-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0025_auto_20200516_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frontal_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontal_image', models.ImageField(blank=True, null=True, upload_to='images/frontal_images/')),
            ],
        ),
    ]
