# Generated by Django 2.2.3 on 2020-05-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0029_auto_20200517_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
