# Generated by Django 2.2.3 on 2020-06-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0031_auto_20200521_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='stock',
            field=models.IntegerField(blank=True, default=1, max_length=100, null=True),
        ),
    ]
