# Generated by Django 2.2.3 on 2020-06-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0032_ad_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
    ]
