# Generated by Django 2.2.3 on 2020-06-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0034_auto_20200609_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ShopApp.Ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ShopApp.Profile')),
            ],
        ),
    ]
