# Generated by Django 2.2.3 on 2020-06-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0038_auto_20200610_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='profile',
        ),
    ]
