# Generated by Django 2.2.3 on 2020-06-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0039_auto_20200610_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='profile',
            new_name='user',
        ),
    ]
